name = "Kanagawa Wave"
variant = "dark"
font = "JetBrains Mono"
ghostty = "Kanagawa Wave"
helix = "kanagawa"
zellij = "kanagawa-wave"
btop = "kanagawa_wave"
neovim = "kanagawa-wave"
delta = "kanagawa-wave"
bat = "Kanagawa"
tmux = "kanagawa-wave"
opencode = "kanagawa"
wezterm = "Kanagawa (Gogh)"
wezterm_font = "wezterm.font 'JetBrainsMono Nerd Font Mono'"
wezterm_bg = "1F1F28"
