name = "Monokai"
variant = "dark"
font = "Fira Code"
ghostty = "Monokai Pro"
helix = "monokai_pro"
zellij = "monokai"
btop = "monokai"
neovim = "monokai-pro"
delta = "monokai"
bat = "Monokai"
tmux = "monokai"
opencode = "monokai"
