name = "Monokai Pro"
variant = "dark"
font = "Fira Code"
ghostty = "Monokai Pro"
helix = "monokai_pro"
zellij = "monokai"
btop = "monokai"
neovim = "monokai-pro"
delta = "monokai"
bat = "Monokai"
tmux = "monokai"
opencode = "monokai"
wezterm = "Monokai Pro (Gogh)"
wezterm_font = "wezterm.font('FiraCode Nerd Font Mono', { weight = 450 })"
wezterm_bg = "2d2a2e"
