[mgr]
cwd = { fg = "#f8f8f2", italic = true }

# Hovered
hovered         = { bg = "#3e3d32" }
preview_hovered = { bg = "#3e3d32" }

# Find
find_keyword  = { fg = "#272822", bg = "#fd971f", bold = true }
find_position = { fg = "#a6e22e", bg = "#3e3d32", bold = true }

# Marker
marker_copied   = { fg = "#a6e22e", bg = "#a6e22e" }
marker_cut      = { fg = "#f92672", bg = "#f92672" }
marker_marked   = { fg = "#ae81ff", bg = "#ae81ff" }
marker_selected = { fg = "#66d9ef", bg = "#66d9ef" }

# Count
count_copied   = { fg = "#272822", bg = "#a6e22e" }
count_cut      = { fg = "#272822", bg = "#f92672" }
count_selected = { fg = "#272822", bg = "#66d9ef" }

# Border
border_symbol = "│"
border_style  = { fg = "#49483e" }

# Tab
[tabs]
active   = { fg = "#272822", bg = "#66d9ef" }
inactive = { fg = "#66d9ef", bg = "#3e3d32" }

[mode]
normal_main = { fg = "#272822", bg = "#66d9ef", bold = true }
normal_alt  = { fg = "#66d9ef", bg = "#3e3d32" }

select_main = { fg = "#272822", bg = "#ae81ff", bold = true }
select_alt  = { fg = "#ae81ff", bg = "#3e3d32" }

unset_main  = { fg = "#272822", bg = "#75715e", bold = true }
unset_alt   = { fg = "#75715e", bg = "#3e3d32" }

[status]
overall   = { fg = "#f8f8f2", bg = "#1e1f1c" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#f8f8f2", bold = true }
progress_normal = { fg = "#49483e", bg = "#3e3d32" }
progress_error  = { fg = "#f92672", bg = "#3e3d32" }

# Permissions
perm_type  = { fg = "#66d9ef" }
perm_read  = { fg = "#e6db74" }
perm_write = { fg = "#f92672" }
perm_exec  = { fg = "#a6e22e" }
perm_sep   = { fg = "#49483e" }

[pick]
border   = { fg = "#49483e" }
active   = { fg = "#f8f8f2",  bg = "#3e3d32" }
inactive = { fg = "#f8f8f2" }

# Input
[input]
border   = { fg = "#a6e22e" }
title    = { fg = "#a6e22e" }
value    = { fg = "#ae81ff" }
selected = { bg = "#3e3d32" }

# Completion
[cmp]
border   = { fg = "#a6e22e" }
active   = { fg = "#f8f8f2", bg = "#49483e" }
inactive = { fg = "#f8f8f2" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#49483e" }
title   = { fg = "#49483e" }
hovered = { fg = "#f8f8f2", bg = "#3e3d32" }

# Which
[which]
cols            = 3
mask            = { bg = "#1e1f1c" }
cand            = { fg = "#a6e22e" }
rest            = { fg = "#66d9ef" }
desc            = { fg = "#ae81ff" }
separator       = " ➜ "
separator_style = { fg = "#75715e" }

# Confirm
[confirm]
border  = { fg = "#a6e22e" }
title   = { fg = "#49483e" }
content = {}
list    = {}
btn_yes = { bg = "#3e3d32" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#49483e" }
title   = { fg = "#49483e" }

# Notify
[notify]
title_info  = { fg = "#a6e22e" }
title_warn  = { fg = "#e6db74" }
title_error = { fg = "#f92672" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#a6e22e" }
run     = { fg = "#ae81ff" }
desc    = { fg = "#66d9ef" }
hovered = { bg = "#3e3d32" }
footer  = { fg = "#f8f8f2", bg = "#272822" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#e6db74" },

	# Media
	{ mime = "{audio,video}/*", fg = "#ae81ff" },

	# Archives
	{ mime = "application/*zip", fg = "#f92672" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f92672" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#66d9ef" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f92672" },
	{ name = "*", is = "exec"  , fg = "#a6e22e" },

	# Fallback
	{ name = "*/", fg = "#66d9ef" },
	{ name = "*", fg = "#f8f8f2" }
]
