name = "Flexoki Dark"
variant = "dark"
font = "Monaspace Argon NF"
ghostty = "Flexoki Dark"
helix = "flexoki_dark"
zellij = "flexoki-dark"
btop = "flexoki_dark"
neovim = "flexoki"
delta = "flexoki-dark"
bat = "Flexoki Dark"
tmux = "flexoki-dark"
opencode = "flexoki-dark"
wezterm = "flexoki-dark"
wezterm_font = "wezterm.font('Monaspace Argon NF', { weight = 'Regular' })"
wezterm_bg = "100f0f"
typora = "flexoki-dark"
