[mgr]
cwd = { fg = "#F8F8F2", italic = true }

# Hovered
hovered         = { bg = "#3E3D32" }
preview_hovered = { bg = "#3E3D32" }

# Find
find_keyword  = { fg = "#272822", bg = "#FD971F", bold = true }
find_position = { fg = "#A6E22E", bg = "#3E3D32", bold = true }

# Marker
marker_copied   = { fg = "#A6E22E", bg = "#A6E22E" }
marker_cut      = { fg = "#F92672", bg = "#F92672" }
marker_marked   = { fg = "#AE81FF", bg = "#AE81FF" }
marker_selected = { fg = "#66D9EF", bg = "#66D9EF" }

# Count
count_copied   = { fg = "#272822", bg = "#A6E22E" }
count_cut      = { fg = "#272822", bg = "#F92672" }
count_selected = { fg = "#272822", bg = "#66D9EF" }

# Border
border_symbol = "|"
border_style  = { fg = "#49483E" }

# Tab
[tabs]
active   = { fg = "#272822", bg = "#66D9EF" }
inactive = { fg = "#66D9EF", bg = "#3E3D32" }

[mode]
normal_main = { fg = "#272822", bg = "#66D9EF", bold = true }
normal_alt  = { fg = "#66D9EF", bg = "#3E3D32" }

select_main = { fg = "#272822", bg = "#AE81FF", bold = true }
select_alt  = { fg = "#AE81FF", bg = "#3E3D32" }

unset_main  = { fg = "#272822", bg = "#75715E", bold = true }
unset_alt   = { fg = "#75715E", bg = "#3E3D32" }

[status]
overall   = { fg = "#F8F8F2", bg = "#1E1F1C" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#F8F8F2", bold = true }
progress_normal = { fg = "#49483E", bg = "#3E3D32" }
progress_error  = { fg = "#F92672", bg = "#3E3D32" }

# Permissions
perm_type  = { fg = "#66D9EF" }
perm_read  = { fg = "#E6DB74" }
perm_write = { fg = "#F92672" }
perm_exec  = { fg = "#A6E22E" }
perm_sep   = { fg = "#49483E" }

[pick]
border   = { fg = "#49483E" }
active   = { fg = "#F8F8F2",  bg = "#3E3D32" }
inactive = { fg = "#F8F8F2" }

# Input
[input]
border   = { fg = "#A6E22E" }
title    = { fg = "#A6E22E" }
value    = { fg = "#AE81FF" }
selected = { bg = "#3E3D32" }

# Completion
[cmp]
border   = { fg = "#A6E22E" }
active   = { fg = "#F8F8F2", bg = "#49483E" }
inactive = { fg = "#F8F8F2" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#49483E" }
title   = { fg = "#49483E" }
hovered = { fg = "#F8F8F2", bg = "#3E3D32" }

# Which
[which]
cols            = 3
mask            = { bg = "#1E1F1C" }
cand            = { fg = "#A6E22E" }
rest            = { fg = "#66D9EF" }
desc            = { fg = "#AE81FF" }
separator       = " > "
separator_style = { fg = "#75715E" }

# Confirm
[confirm]
border  = { fg = "#A6E22E" }
title   = { fg = "#49483E" }
content = {}
list    = {}
btn_yes = { bg = "#3E3D32" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#49483E" }
title   = { fg = "#49483E" }

# Notify
[notify]
title_info  = { fg = "#A6E22E" }
title_warn  = { fg = "#E6DB74" }
title_error = { fg = "#F92672" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#A6E22E" }
run     = { fg = "#AE81FF" }
desc    = { fg = "#66D9EF" }
hovered = { bg = "#3E3D32" }
footer  = { fg = "#F8F8F2", bg = "#272822" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#E6DB74" },

	# Media
	{ mime = "{audio,video}/*", fg = "#AE81FF" },

	# Archives
	{ mime = "application/*zip", fg = "#F92672" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#F92672" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#66D9EF" },

	# Special files
	{ name = "*", is = "orphan", bg = "#F92672" },
	{ name = "*", is = "exec"  , fg = "#A6E22E" },

	# Fallback
	{ name = "*/", fg = "#66D9EF" },
	{ name = "*", fg = "#F8F8F2" }
]
