gui:
  border: hidden
  containerStatusHealthStyle: icon
reporting: "off"
gui:
  theme:
    activeBorderColor:
      - "#FD971F"
      - bold
    inactiveBorderColor:
      - "#49483E"
    selectedLineBgColor:
      - "#3E3D32"
    optionsTextColor:
      - "#66D9EF"
